function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 24-Mar-2018 02:18:57

close all

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 5.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 5.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'FontSize',20,'Layer','top','XTick',[1 2 3 4 5],'XTickLabel',...
    {'Rest','Thumb','Index','Middle','Ring and Pinkie'},'YTick',[1 2 3 4 5],...
    'YTickLabel',{'Rest','Thumb','Index','Middle','Ring and Pinkie'});
% Create colorbar
colorbar('peer',axes1);

